version: '3'

vars:
  REGISTRY: ghcr.io/nce
  IMAGE_NAME: kubewreck

tasks:
  air:
    desc: Build local binary
    dir: app/
    cmd: 
      air --build.cmd "go build -o bin/app -ldflags='-X main.version=foo'" --build.bin "./bin/app"
  build:
    desc: Build images
    dir: app/
    cmds:
    - docker buildx build
        --builder naughty_benz
        --build-arg APP_VERSION="v1"
        --platform linux/amd64
        --platform linux/arm64
        --push
        --tag {{.REGISTRY}}/{{.IMAGE_NAME}}:v1 .
    - docker buildx build
        --builder naughty_benz
        --build-arg APP_VERSION="v2"
        --platform linux/amd64
        --push
        --tag {{.REGISTRY}}/{{.IMAGE_NAME}}:v2 .
  push:
    desc: Push images to github
    cmd: 
    cmds:
    - gh auth token | docker login ghcr.io --username $(whoami) --password-stdin
    #- gh auth token | container registry login ghcr.io --username $(whoami) --password-stdin
    - for: 
        matrix:
          PLATFORM: 
          - linux/amd64
          - linux/arm64
          VERSION: 
          - v1
      cmd: 
        docker image push
          --platform {{.ITEM.PLATFORM}}
          {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.ITEM.VERSION}}
    - docker image push
        --platform "linux/amd64"
        {{.REGISTRY}}/{{.IMAGE_NAME}}:v2
